//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdmxConverter.Logic.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdmxConverter.Logic.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x1F8B080000000000000BCC57DB6E1B37107D2FD07F20F8D4028E683B2FADB19BC095ADC06864075927EFD4EE4826CACB861743FAB63EF493FA0B1DEE5DBB9615274551183096DC993333876786ABBFFFFC2B79BB55923C8275C2E8949ECD4E29019D9B42E84D4A835FBFFA85BE7DF3E30FC975A1B6E4736BF73ADAA1A776297DF0BEBC60CCE50FA0B89B29915BE3CCDACF72A3182F0C3B3F3DFD959D9D3140088A5884241F83F64241B5C0E5DCE81C4A1FB85C9A02A46BF6F14D56A1925BAEC0953C8794665C9512AEB8E72BEE60D62C5708E161EB29B99482635619C835255C6BE3B9C79C2F3E39C8BC357A9395B8C1E5FDAE04B45B73E9A0A9E5A237FFDA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleDatabaseEdmx {
            get {
                return ResourceManager.GetString("SampleDatabaseEdmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAAC8xX224bNxB9L9B/IPjUAo5oOy+tsZvAla3AaGQHWSfv1O5IJsrLhhdD+rY+9JP6Cx3uXbuWFSdFURgwltyZMzOHZ4arv//8K3m7VZI8gnXC6JSezU4pAZ2bQuhNSoNfv/qFvn3z4w/JdaG25HNr9zraoad2KX3wvrxgzOUPoLibKZFb48zaz3KjGC8MOz89/ZWdnTFACIpYhCQfg/ZCQbXA5dzoHEofuFyaAqRr9vFNVqGSW67AlTyHlGZclRKuuOcr7mDWLFcI4WHrKbmUgmNWGcg1JVxr47nHnC8+Oci8NXqTlbjB5f2uBLRbc+mgqeWiN//ask7PY1msd2yh8uC8US8EPHvd8MTG7t/Edk12w+Q1Mu53seqKzZQujKFkHOdiLm20OcbzrIIT4GYIc0L2jU86oaCe4t8JmQfpg4VUQ/CWyxPyIaykyH+H3b35A3Sqg5TDdDFhfLe3gVsfrCnB+t1HWDdF3BSUsH0/Nnbs3AY+dY3v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleResourceEdmx {
            get {
                return ResourceManager.GetString("SampleResourceEdmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Edmx Version=&quot;3.0&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edmx&quot;&gt;
        ///  &lt;Runtime&gt;
        ///    &lt;ConceptualModels&gt;
        ///      &lt;Schema Namespace=&quot;SampleDatabase.SampleDbContext&quot; Alias=&quot;Self&quot; annotation:UseStrongSpatialTypes=&quot;false&quot; xmlns:annotation=&quot;http://schemas.microsoft.com/ado/2009/02/edm/annotation&quot; xmlns:customannotation=&quot;http://schemas.microsoft.com/ado/2013/11/edm/customannotation&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot;&gt;
        ///        &lt;EntityType Name=&quot;Foo&quot; customannotation:ClrType=&quot;SampleDatabase [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleXmlEdmx {
            get {
                return ResourceManager.GetString("SampleXmlEdmx", resourceCulture);
            }
        }
    }
}
