//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdmxConverter.DomainLogic.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdmxConverter.DomainLogic.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x1F8B0800000000000400CD57DB6EDB38107D5F60FF81E0D31648C5247DD906528BD4898BA075525469DF6969EC10CB8BCA4B607F5B1FFA49FB0B3BBACB521CB7E9A228020422357366E6F0CC50FEF7EBB7F8F54649720FD609A3137A121D53023A33B9D0EB8406BF7AFE377DFDEACF3FE2CB5C6DC8E7D6EE4569879EDA25F4CEFBE28C3197DD81E22E5222B3C699958F32A318CF0D3B3D3E7EC94E4E182004452C42E28F417BA1A05AE072667406850F5C2E4C0ED235FBF826AD50C93557E00A9E414253AE0A0917DCF325771035CB254278D8784ACEA5E098550A724509D7DA78EE31E7B34F0E526F8D5EA7056E7079BB2D00ED565C3A686A39EBCDBFB7AC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleDatabaseEdmx {
            get {
                return ResourceManager.GetString("SampleDatabaseEdmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAM1X227bOBB9X2D/geDTFkjFJH3ZBlKL1ImLoHVSVGnfaWnsEMuLyktgf1sf+kn7Czu6y1Ict+miKAIEIjVzZubwzFD+9+u3+PVGSXIP1gmjE3oSHVMCOjO50OuEBr96/jd9/erPP+LLXG3I59buRWmHntol9M774owxl92B4i5SIrPGmZWPMqMYzw07PT5+yU5OGCAERSxC4o9Be6GgWuByZnQGhQ9cLkwO0jX7+CatUMk1V+AKnkFCU64KCRfc8yV3EDXLJUJ42HhKzqXgmFUKckUJ19p47jHns08OUm+NXqcFbnB5uy0A7VZcOmhqOevNv7es49OyLNY7tlBZcN6oHwQ8edHwxMbuT2Kbdjwik5fIuN+WVVdsJnRuDCXjOGczaUubQzxHFZwAFyHMEdk1PuqEgnoq/47ILEgfLCQagrdcHpEPYSlF9g62t+Yf0IkOUg7TxYTx3c4Gbn2wpgDrtx9h1RRxlVPCdv3Y2LFzG/jUNb4N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleResourceEdmx {
            get {
                return ResourceManager.GetString("SampleResourceEdmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Edmx Version=&quot;3.0&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/databaseEdmx&quot;&gt;
        ///  &lt;Runtime&gt;
        ///    &lt;ConceptualModels&gt;
        ///      &lt;Schema Namespace=&quot;SampleDatabase.SampleDbContext&quot; Alias=&quot;Self&quot; annotation:UseStrongSpatialTypes=&quot;false&quot; xmlns:annotation=&quot;http://schemas.microsoft.com/ado/2009/02/edm/annotation&quot; xmlns:customannotation=&quot;http://schemas.microsoft.com/ado/2013/11/edm/customannotation&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot;&gt;
        ///        &lt;EntityType Name=&quot;Foo&quot; customannotation:ClrType=&quot;Sample [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleXmlEdmx {
            get {
                return ResourceManager.GetString("SampleXmlEdmx", resourceCulture);
            }
        }
    }
}
