// <auto-generated />
namespace SampleDatabase.SampleDbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_101));
        
        string IMigrationMetadata.Id
        {
            get { return "201708061947384_1.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
