//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleDatabase.SampleDbContext.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201708061947384_1_0_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _201708061947384_1_0_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleDatabase.SampleDbContext.Migrations.201708061947384_1.0.1", typeof(_201708061947384_1_0_1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEANVZ3W7bNhS+H7B3IHi1AallpzebYbdInbgI1sRBnBa7C2jp2CFGUSpJBTaKPdku9kh7hR3qz5IoxT9N0w0BApvk+XjO4XeOPsr//PX36O06FOQRlOaRHNNBr08JSD8KuFyNaWKWr36hb9/8+MPoIgjX5FOx7rVdh5ZSj+mDMfHQ87T/ACHTvZD7KtLR0vT8KPRYEHmn/f6v3mDgAUJQxCJkdJtIw0NIv+DXSSR9iE3CxFUUgND5OM7MU1RyzULQMfNhTOcsjAWcM8MWTEMv/7pACANrQ8mZ4Ay9moNYUsKkjAwz6PPwo4a5UZFczWMcYOJuEwOuWzKhIY9luF2+b1j9UxuWtzUsoPxEmyg8EHDwOs+T1zQ/Ktu0zCNm8gIzbjY26jSbY/qOKUqa+wwnQtk1u/LcS+E46B7CnJD64pOSKMgn+3dCJokwiYKxhMQoJk7ITbIQ3P8NNnfRHyDHMhGi6i46jHO1ARy6UVEMymxuYZkHMY2i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
